# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import p2p_msg_pb2 as p2p__msg__pb2


class PeerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Msg = channel.stream_stream(
                '/Peer/Msg',
                request_serializer=p2p__msg__pb2.PeerMessage.SerializeToString,
                response_deserializer=p2p__msg__pb2.PeerMessage.FromString,
                )


class PeerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Msg(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Msg': grpc.stream_stream_rpc_method_handler(
                    servicer.Msg,
                    request_deserializer=p2p__msg__pb2.PeerMessage.FromString,
                    response_serializer=p2p__msg__pb2.PeerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Peer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Peer(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Msg(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Peer/Msg',
            p2p__msg__pb2.PeerMessage.SerializeToString,
            p2p__msg__pb2.PeerMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
