# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p2p-msg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='p2p-msg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rp2p-msg.proto\"7\n\x0bPeerMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t2/\n\x04Peer\x12\'\n\x03Msg\x12\x0c.PeerMessage\x1a\x0c.PeerMessage\"\x00(\x01\x30\x01\x62\x06proto3'
)




_PEERMESSAGE = _descriptor.Descriptor(
  name='PeerMessage',
  full_name='PeerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PeerMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='PeerMessage.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='PeerMessage.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['PeerMessage'] = _PEERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PeerMessage = _reflection.GeneratedProtocolMessageType('PeerMessage', (_message.Message,), {
  'DESCRIPTOR' : _PEERMESSAGE,
  '__module__' : 'p2p_msg_pb2'
  # @@protoc_insertion_point(class_scope:PeerMessage)
  })
_sym_db.RegisterMessage(PeerMessage)



_PEER = _descriptor.ServiceDescriptor(
  name='Peer',
  full_name='Peer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=74,
  serialized_end=121,
  methods=[
  _descriptor.MethodDescriptor(
    name='Msg',
    full_name='Peer.Msg',
    index=0,
    containing_service=None,
    input_type=_PEERMESSAGE,
    output_type=_PEERMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PEER)

DESCRIPTOR.services_by_name['Peer'] = _PEER

# @@protoc_insertion_point(module_scope)
